version: '3.8'

services:
  db:
    image: kartoza/postgis
    container_name: postgis_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: osm
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - postgis-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgis-data: